src/components/Header.js

Refactoring the `Header` component
- Remove some HTML tags that are not necessary
- Destructuring the Header component props
- Capitalize the Header component name

Refactor Header Component

---

src/components/Progress.js
src/components/ProgressWrapper.js

Refactoring the `Progress` component. The whole idea is to separate concerns. The component will only render the HTML and the functions will handle logic and data.
- Remove some code: static method and component default state
- Extract the progress style logic into a function & cleanup the component
- Add a ProgressWrapper component
It would be great to add [unit tests](https://github.com/mohitk05/react-insta-stories/issues/18) to these functions and components.

Refactor Progress component

---

example/src/App.js
src/components/Story.tsx
src/interfaces.tsx

Provide a `content: (action) => return <div>Hello!</div>` in the story object to render custom content.

Added feature for rendering content: function

---

.gitignore
packages/react-insta-stories/README.md
packages/react-insta-stories/example/src/App.js
packages/react-insta-stories/src/components/Container.tsx
packages/react-insta-stories/src/index.tsx
packages/react-insta-stories/src/interfaces.tsx

Following props added:
- `isPaused `
- `currentIndex`
- `onStoryStart`
- `onStoryEnd`
- `onAllStoriesEnd`

Story completion callback, additional props

---

packages/react-insta-stories/example/src/App.css
packages/react-insta-stories/example/src/App.js
packages/react-insta-stories/package-lock.json
packages/react-insta-stories/package.json
packages/react-insta-stories/src/components/Container.tsx
packages/react-insta-stories/src/components/Progress.tsx
packages/react-insta-stories/src/components/ProgressArray.tsx
packages/react-insta-stories/src/components/ProgressWrapper.tsx
packages/react-insta-stories/src/components/Story.tsx
packages/react-insta-stories/src/styles.css
packages/react-insta-stories/src/styles.css.d.ts
packages/react-insta-stories/webpack.config.js

Fixed the issue of CSS files import.

CSS import fixed

---

packages/react-insta-stories/README.md
packages/react-insta-stories/example/src/App.js
packages/react-insta-stories/src/components/SeeMore.tsx
packages/react-insta-stories/src/components/Story.tsx
packages/react-insta-stories/src/interfaces.tsx

SeeMore feature updated. Now accepts a function to rendered which receives a `close` function as a prop, to close the SeeMore popup.

Updated SeeMore feature

---

example/webpack.config.js
package.json
src/renderers/Default.tsx

Default renderer was incorrectly written, fixed that to a blank story with a message.

Fixed default renderer loading

---

src/components/Story.tsx

With  `alignItems: 'center'` story images will be always centered

Center images

---

src/renderers/Video.tsx

fix: Videos doesn't work on iOS devices

---

example/src/App.css
example/src/App.js
example/src/index.ejs
package.json
src/components/Container.tsx
src/components/ProgressArray.tsx

Fix for #130 
Comments on the issue about the problem, added a fix to check if the `Container` component is mounted and only proceed if it is.

Fix for issue #130, added mounted check

---

src/components/Container.tsx

Fix for #127 
Potential issue due to passive event listeners.

Fix for issue #127

---

src/components/ProgressArray.tsx
src/renderers/Video.tsx

Reverts mohitk05/react-insta-stories#159

Revert "iOS bugfixes"

---

README.md
src/components/Container.tsx
src/index.tsx
src/interfaces.tsx

[feature] add new prop 'preventDefault' to disable the default behavior

---

README.md

Dysperse, my all-in-one productivity platform uses `react-insta-stories`! 🔥🔥🔥
https://dysperse.com

Add my site to README.md

---

example/package-lock.json
package.json

Update version to v2.5.0

---

package.json

Update version to 2.5.2

---

package-lock.json
package.json

Version 2.5.7

---

example/webpack.config.js
package-lock.json
package.json
src/components/Container.tsx

Fix safari long press

---

package-lock.json
package.json
src/components/ProgressArray.tsx

Update the lastTime ref when the story starts playing.

Update the lastTime ref when the story starts playing

---

src/interfaces.tsx
src/renderers/Video.tsx

Hey! I added this so I could bring up videos that were muted by default. Let me know if this is okay / if you need aditional docs / changes for this!

Add muted? to Story interface

---

package.json

* Updates version to v2.7.0 after merging #311

Update package.json - v2.7.0
